### ISSUE TITLE
Add pip requirements.txt files for dependencies

### ISSUE THREAD

**Issue by gingeleski** [nathanlopez/Stitch#2]
Exporting dependencies into requirements.txt files for pip would streamline setup.

`pip freeze > requirements.txt`

Three different files may be required since dependencies differ amongst OS (i.e. win_requirements.txt, osx_requirements.txt ...).

And then new users would just clone, set up a Python 2.7 virtual environment, and go
`pip install -r win_requirements.txt`

**Comment by nathanlopez** [comment]
Awesome, thanks for the insight. I appreciate it :]
