### ISSUE TITLE
cstringIO problem 

### ISSUE THREAD

**Issue by asura132** [nathanlopez/Stitch#27]
please help
keep getting this errors from win_requirements.txt

**Comment by Ekultek** [comment]
Follow this https://github.com/nathanlopez/Stitch/issues/14

**Comment by asura132** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\user>cd c:\Stitch-master

c:\Stitch-master>pip install email
Collecting email
  Using cached email-4.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\python\lib\site-packages\setuptools\__init__.py", line 12, in <mo
dule>
        import setuptools.version
      File "c:\python\lib\site-packages\setuptools\version.py", line 1, in <modu
le>
        import pkg_resources
      File "c:\python\lib\site-packages\pkg_resources\__init__.py", line 36, in
<module>
        import email.parser
      File "C:\Users\user\AppData\Local\Temp\pip-build-cmozwuoe\email\email\pars
er.py", line 10, in <module>
        from cStringIO import StringIO
    ModuleNotFoundError: No module named 'cStringIO'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\App
Data\Local\Temp\pip-build-cmozwuoe\email\

look at this

**Comment by Ekultek** [comment]
There is no pip install email in my guide on installing on Windows

**Comment by Ekultek** [comment]
Try pip uninstall email, pip install pip --upgrade, pip install email

**Comment by asura132** [comment]
i just showed you my problem 
is this "Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\App
Data\Local\Temp\pip-build-cmozwuoe\email\"

okay ill try that

**Comment by asura132** [comment]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\user>pip install email
Collecting email
  Using cached email-4.0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\python\setuptools\__init__.py", line 12, in <module>
        import setuptools.version
      File "c:\python\setuptools\version.py", line 1, in <module>
        import pkg_resources
      File "c:\python\pkg_resources\__init__.py", line 36, in <module>
        import email.parser
      File "C:\Users\user\AppData\Local\Temp\pip-build-knpovk2u\email\email\pars
er.py", line 10, in <module>
        from cStringIO import StringIO
    ModuleNotFoundError: No module named 'cStringIO'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\App
Data\Local\Temp\pip-build-knpovk2u\email\

C:\Users\user>

same shit over and over again huhuhuhu

**Comment by Ekultek** [comment]
Well what python version are you running? If you're running 3.x then it won't work, stringio was replaced with io.stringio. Get a VM and try running it on Linux

**Comment by asura132** [comment]
okay

**Comment by asura132** [comment]
thanks, im using it right now
